export const crimeData = [
    {
        crime_id: '001',
        type: 'Theft',
        date: '2023-10-15',
        location: {
            address: '123 Main St',
            city: 'New York',
            state: 'NY',
            zip_code: '10001',
        },
        description: 'Stolen bicycle from front porch.',
        status: 'Open',
    },
    {
        crime_id: '002',
        type: 'Assault',
        date: '2023-10-14',
        location: {
            address: '456 Elm St',
            city: 'Los Angeles',
            state: 'CA',
            zip_code: '90001',
        },
        description: 'Physical altercation at a bar.',
        status: 'Under Investigation',
    },
    {
        crime_id: '003',
        type: 'Burglary',
        date: '2023-10-13',
        location: {
            address: '789 Oak Ave',
            city: 'Chicago',
            state: 'IL',
            zip_code: '60601',
        },
        description: 'Break-in at residential property during the night.',
        status: 'Closed',
    },
    {
        crime_id: '004',
        type: 'Fraud',
        date: '2023-10-12',
        location: {
            address: '321 Pine St',
            city: 'Houston',
            state: 'TX',
            zip_code: '77001',
        },
        description: 'Credit card fraud reported by victim.',
        status: 'Open',
    },
    {
        crime_id: '005',
        type: 'Vandalism',
        date: '2023-10-11',
        location: {
            address: '654 Maple Rd',
            city: 'San Francisco',
            state: 'CA',
            zip_code: '94101',
        },
        description: 'Graffiti on public property.',
        status: 'Under Investigation',
    },
    {
        crime_id: '006',
        type: 'Robbery',
        date: '2023-10-10',
        location: {
            address: '987 Cedar Blvd',
            city: 'Seattle',
            state: 'WA',
            zip_code: '98101',
        },
        description: 'Armed robbery at convenience store.',
        status: 'Closed',
    },
    {
        crime_id: '007',
        type: 'Drug Possession',
        date: '2023-10-09',
        location: {
            address: '123 Birch Ln',
            city: 'Miami',
            state: 'FL',
            zip_code: '33101',
        },
        description: 'Illegal substances found during routine traffic stop.',
        status: 'Open',
    },
    {
        crime_id: '008',
        type: 'Cybercrime',
        date: '2023-10-08',
        location: {
            address: '456 Spruce St',
            city: 'Austin',
            state: 'TX',
            zip_code: '73301',
        },
        description: 'Phishing attack targeting local businesses.',
        status: 'Under Investigation',
    },
    {
        crime_id: '009',
        type: 'Arson',
        date: '2023-10-07',
        location: {
            address: '789 Walnut Rd',
            city: 'Denver',
            state: 'CO',
            zip_code: '80201',
        },
        description: 'Fire set intentionally at abandoned warehouse.',
        status: 'Closed',
    },
    {
        crime_id: '010',
        type: 'Kidnapping',
        date: '2023-10-06',
        location: {
            address: '321 Chestnut Ave',
            city: 'Atlanta',
            state: 'GA',
            zip_code: '30301',
        },
        description: 'Child reported missing; suspected abduction.',
        status: 'Open',
    },
    {
        crime_id: '011',
        type: 'Stalking',
        date: '2023-10-05',
        location: {
            address: '654 Willow St',
            city: 'Boston',
            state: 'MA',
            zip_code: '02101',
        },
        description: 'Repeated harassment of victim by known individual.',
        status: 'Under Investigation',
    },
    {
        crime_id: '012',
        type: 'Identity Theft',
        date: '2023-10-04',
        location: {
            address: '987 Redwood Blvd',
            city: 'Phoenix',
            state: 'AZ',
            zip_code: '85001',
        },
        description: 'Personal information stolen and used fraudulently.',
        status: 'Open',
    },
    {
        crime_id: '013',
        type: 'Homicide',
        date: '2023-10-03',
        location: {
            address: '123 Aspen Ln',
            city: 'Philadelphia',
            state: 'PA',
            zip_code: '19101',
        },
        description: 'Suspicious death under investigation.',
        status: 'Closed',
    },
    {
        crime_id: '014',
        type: 'Trespassing',
        date: '2023-10-02',
        location: {
            address: '456 Magnolia St',
            city: 'Dallas',
            state: 'TX',
            zip_code: '75201',
        },
        description: 'Unauthorized person entered private property.',
        status: 'Open',
    },
    {
        crime_id: '015',
        type: 'Shoplifting',
        date: '2023-10-01',
        location: {
            address: '789 Poplar Rd',
            city: 'San Diego',
            state: 'CA',
            zip_code: '92101',
        },
        description: 'Items stolen from retail store.',
        status: 'Under Investigation',
    },
    {
        crime_id: '016',
        type: 'Sexual Assault',
        date: '2023-09-30',
        location: {
            address: '321 Dogwood Ave',
            city: 'Las Vegas',
            state: 'NV',
            zip_code: '89101',
        },
        description: 'Victim reported assault at public park.',
        status: 'Open',
    },
    {
        crime_id: '017',
        type: 'Public Intoxication',
        date: '2023-09-29',
        location: {
            address: '654 Cypress St',
            city: 'Portland',
            state: 'OR',
            zip_code: '97201',
        },
        description: 'Individual arrested for disorderly conduct.',
        status: 'Closed',
    },
    {
        crime_id: '018',
        type: 'Extortion',
        date: '2023-09-28',
        location: {
            address: '987 Palm Blvd',
            city: 'Charlotte',
            state: 'NC',
            zip_code: '28201',
        },
        description: 'Business owner threatened for money.',
        status: 'Open',
    },
    {
        crime_id: '019',
        type: 'Carjacking',
        date: '2023-09-27',
        location: {
            address: '123 Sequoia Ln',
            city: 'Indianapolis',
            state: 'IN',
            zip_code: '46201',
        },
        description: 'Vehicle stolen at gunpoint.',
        status: 'Under Investigation',
    },
    {
        crime_id: '020',
        type: 'Harassment',
        date: '2023-09-26',
        location: {
            address: '456 Hickory St',
            city: 'Columbus',
            state: 'OH',
            zip_code: '43201',
        },
        description: 'Repeated threatening calls received.',
        status: 'Open',
    },
    {
        crime_id: '021',
        type: 'Drug Trafficking',
        date: '2023-09-25',
        location: {
            address: '789 Sycamore Rd',
            city: 'Detroit',
            state: 'MI',
            zip_code: '48201',
        },
        description: 'Large quantity of illegal drugs seized.',
        status: 'Under Investigation',
    },
    {
        crime_id: '022',
        type: 'Disorderly Conduct',
        date: '2023-09-24',
        location: {
            address: '321 Fir Ave',
            city: 'Memphis',
            state: 'TN',
            zip_code: '38101',
        },
        description: 'Disturbance reported at public event.',
        status: 'Closed',
    },
    {
        crime_id: '023',
        type: 'Hate Crime',
        date: '2023-09-23',
        location: {
            address: '654 Beech St',
            city: 'Baltimore',
            state: 'MD',
            zip_code: '21201',
        },
        description: 'Graffiti with hateful symbols on private property.',
        status: 'Under Investigation',
    },
    {
        crime_id: '024',
        type: 'Domestic Violence',
        date: '2023-09-22',
        location: {
            address: '987 Juniper Blvd',
            city: 'Milwaukee',
            state: 'WI',
            zip_code: '53201',
        },
        description: 'Report of assault by spouse in a residence.',
        status: 'Open',
    },
    {
        crime_id: '025',
        type: 'Pickpocketing',
        date: '2023-09-21',
        location: {
            address: '123 Cedar Ln',
            city: 'Nashville',
            state: 'TN',
            zip_code: '37201',
        },
        description: 'Wallet stolen in crowded subway station.',
        status: 'Closed',
    },
    {
        crime_id: '026',
        type: 'Hit and Run',
        date: '2023-09-20',
        location: {
            address: '456 Pine St',
            city: 'Kansas City',
            state: 'MO',
            zip_code: '64101',
        },
        description: 'Vehicle fled scene after striking pedestrian.',
        status: 'Under Investigation',
    },
    {
        crime_id: '027',
        type: 'Animal Cruelty',
        date: '2023-09-19',
        location: {
            address: '789 Dogwood Rd',
            city: 'Salt Lake City',
            state: 'UT',
            zip_code: '84101',
        },
        description: 'Animal abuse reported in residential area.',
        status: 'Open',
    },
    {
        crime_id: '028',
        type: 'Weapon Possession',
        date: '2023-09-18',
        location: {
            address: '321 Maple Ave',
            city: 'Cleveland',
            state: 'OH',
            zip_code: '44101',
        },
        description: 'Illegal firearm found during routine traffic stop.',
        status: 'Closed',
    },
    {
        crime_id: '029',
        type: 'Prostitution',
        date: '2023-09-17',
        location: {
            address: '654 Elm St',
            city: 'New Orleans',
            state: 'LA',
            zip_code: '70101',
        },
        description: 'Suspected solicitation in downtown area.',
        status: 'Under Investigation',
    },
    {
        crime_id: '030',
        type: 'Forgery',
        date: '2023-09-16',
        location: {
            address: '987 Walnut Blvd',
            city: 'Minneapolis',
            state: 'MN',
            zip_code: '55401',
        },
        description: 'Counterfeit checks used at local business.',
        status: 'Open',
    },
    {
        crime_id: '031',
        type: 'DUI',
        date: '2023-09-15',
        location: {
            address: '123 Redwood Ln',
            city: 'Fort Worth',
            state: 'TX',
            zip_code: '76101',
        },
        description: 'Driver arrested for operating under influence.',
        status: 'Closed',
    },
    {
        crime_id: '032',
        type: 'Car Theft',
        date: '2023-09-14',
        location: {
            address: '456 Aspen St',
            city: 'El Paso',
            state: 'TX',
            zip_code: '79901',
        },
        description: 'Vehicle stolen from public parking lot.',
        status: 'Under Investigation',
    },
    {
        crime_id: '033',
        type: 'Child Abuse',
        date: '2023-09-13',
        location: {
            address: '789 Chestnut Rd',
            city: 'Oklahoma City',
            state: 'OK',
            zip_code: '73101',
        },
        description: 'School reported signs of physical abuse in student.',
        status: 'Open',
    },
    {
        crime_id: '034',
        type: 'Tax Evasion',
        date: '2023-09-12',
        location: {
            address: '321 Poplar Ave',
            city: 'Louisville',
            state: 'KY',
            zip_code: '40201',
        },
        description: 'Business under investigation for failure to pay taxes.',
        status: 'Under Investigation',
    },
    {
        crime_id: '035',
        type: 'Counterfeiting',
        date: '2023-09-11',
        location: {
            address: '654 Cypress St',
            city: 'Albuquerque',
            state: 'NM',
            zip_code: '87101',
        },
        description: 'Fake currency discovered at local bank.',
        status: 'Closed',
    },
    {
        crime_id: '036',
        type: 'Armed Assault',
        date: '2023-09-10',
        location: {
            address: '987 Palm Blvd',
            city: 'Tucson',
            state: 'AZ',
            zip_code: '85701',
        },
        description: 'Victim attacked with weapon in parking lot.',
        status: 'Open',
    },
    {
        crime_id: '037',
        type: 'Burglary',
        date: '2023-09-09',
        location: {
            address: '123 Birch Ln',
            city: 'Fresno',
            state: 'CA',
            zip_code: '93650',
        },
        description: 'Residential property broken into overnight.',
        status: 'Under Investigation',
    },
    {
        crime_id: '038',
        type: 'Money Laundering',
        date: '2023-09-08',
        location: {
            address: '456 Spruce St',
            city: 'Sacramento',
            state: 'CA',
            zip_code: '94203',
        },
        description: 'Illegal transfer of funds through shell companies.',
        status: 'Open',
    },
    {
        crime_id: '039',
        type: 'Vehicle Tampering',
        date: '2023-09-07',
        location: {
            address: '789 Oak Rd',
            city: 'Long Beach',
            state: 'CA',
            zip_code: '90802',
        },
        description: 'Car tires slashed in public parking area.',
        status: 'Closed',
    },
    {
        crime_id: '040',
        type: 'Human Trafficking',
        date: '2023-09-06',
        location: {
            address: '321 Pine St',
            city: 'Mesa',
            state: 'AZ',
            zip_code: '85201',
        },
        description: 'Suspected trafficking operation discovered in motel.',
        status: 'Under Investigation',
    },
    {
        crime_id: '041',
        type: 'Arson',
        date: '2023-09-05',
        location: {
            address: '654 Maple Rd',
            city: 'Virginia Beach',
            state: 'VA',
            zip_code: '23450',
        },
        description: 'Fire set at local community center.',
        status: 'Open',
    },
    {
        crime_id: '042',
        type: 'Cybercrime',
        date: '2023-09-04',
        location: {
            address: '987 Cedar Blvd',
            city: 'Raleigh',
            state: 'NC',
            zip_code: '27601',
        },
        description: 'Ransomware attack on healthcare provider.',
        status: 'Closed',
    },
    {
        crime_id: '043',
        type: 'Robbery',
        date: '2023-09-03',
        location: {
            address: '123 Sequoia Ln',
            city: 'Oakland',
            state: 'CA',
            zip_code: '94601',
        },
        description: 'Convenience store robbed at gunpoint.',
        status: 'Under Investigation',
    },
    {
        crime_id: '044',
        type: 'Homicide',
        date: '2023-09-02',
        location: {
            address: '456 Hickory St',
            city: 'Miami',
            state: 'FL',
            zip_code: '33101',
        },
        description: 'Suspicious death in apartment complex.',
        status: 'Open',
    },
    {
        crime_id: '045',
        type: 'Vandalism',
        date: '2023-09-01',
        location: {
            address: '789 Sycamore Rd',
            city: 'Boston',
            state: 'MA',
            zip_code: '02101',
        },
        description: 'Windows of parked vehicles smashed.',
        status: 'Closed',
    },
    {
        crime_id: '046',
        type: 'Fraud',
        date: '2023-08-31',
        location: {
            address: '321 Fir Ave',
            city: 'Seattle',
            state: 'WA',
            zip_code: '98101',
        },
        description: 'Scam targeting elderly residents reported.',
        status: 'Under Investigation',
    },
    {
        crime_id: '047',
        type: 'Theft',
        date: '2023-08-30',
        location: {
            address: '654 Beech St',
            city: 'Denver',
            state: 'CO',
            zip_code: '80201',
        },
        description: 'Electronics stolen from office building.',
        status: 'Open',
    },
    {
        crime_id: '048',
        type: 'Assault',
        date: '2023-08-29',
        location: {
            address: '987 Juniper Blvd',
            city: 'Portland',
            state: 'OR',
            zip_code: '97201',
        },
        description: 'Fight broke out at public park.',
        status: 'Closed',
    },
    {
        crime_id: '049',
        type: 'Forgery',
        date: '2023-08-28',
        location: {
            address: '123 Cedar Ln',
            city: 'Chicago',
            state: 'IL',
            zip_code: '60601',
        },
        description: 'Fake IDs discovered during traffic stop.',
        status: 'Under Investigation',
    },
    {
        crime_id: '050',
        type: 'Drug Possession',
        date: '2023-08-27',
        location: {
            address: '456 Pine St',
            city: 'Phoenix',
            state: 'AZ',
            zip_code: '85001',
        },
        description: 'Narcotics found during vehicle search.',
        status: 'Open',
    },
];
